#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:10:00
#PBS -N 3Dpialwm
#PBS -V

rm -f finished
rm -rf surfaces

module load singularity 2> /dev/null

echo "converting pial and white matter surfaces"

mkdir surfaces

time singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./convertfiles.sh"

count=$(ls surfaces/* | wc -l)

if [ "$count" == 8 ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
