#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:10:00
#PBS -N 3Dpialwm
#PBS -V

rm -f finished
rm -rf surfaces

module load singularity 2> /dev/null

echo "converting pial and white matter surfaces"

mkdir surfaces

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
        docker://brainlife/freesurfer_on_mcr:6.0.2 ./convertfiles.sh

count=$(ls surfaces/* | wc -l)

if [ "$count" == 8 ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
